use_frameworks!

target 'InstagramApp' do #Your app name in 'InstagramApp'

    pod 'FBSDKCoreKit', '~> 4.22.1'
    pod 'FBSDKLoginKit', '~> 4.22.1'
    pod 'FBSDKShareKit', '~> 4.22.1'
    pod 'SDWebImage', '~>3.8'
    pod 'Alamofire', '~> 4.4'

end
